package expander

import (
	"strconv"
	"strings"
)

// EmitGenerated emits Go syntax for AST data only. It never substitutes source
// text into source text; values are serialized as Go literals in a typed tree.
func EmitGenerated(ir ExpandedIR) []byte {
	var out strings.Builder
	out.WriteString("// Code generated by gooo-staged-quasiquote-slice; DO NOT EDIT.\n")
	out.WriteString("// semantic-authority: .gooo/staged-quasiquote.gooo\n")
	out.WriteString("// expansion-output: structured AST data only\n")
	out.WriteString("package main\n\n")
	out.WriteString("import \"fmt\"\n\n")
	out.WriteString("type ASTNode struct {\n")
	out.WriteString("\tKind string\n\tID string\n\tOriginalName string\n\tEffectiveName string\n\tValue string\n\tStage int\n\tOriginIdentity string\n\tStableIdentity string\n\tCaptureDecision string\n\tChildren []ASTNode\n")
	out.WriteString("}\n\n")
	out.WriteString("type ProofStep struct {\n\tStep string\n\tFrom string\n\tTo string\n\tRule string\n\tNodeID string\n\tFromStage int\n\tToStage int\n}\n\n")
	out.WriteString("type TerminalRecord struct {\n")
	out.WriteString("\tSchema string\n\tDecision string\n\tStage string\n\tStep string\n\tReason string\n\tUnknownClass string\n\tNextOperation string\n\tBlockedBy []string\n\tCounterexample string\n\tCounterexampleDigest string\n\tPhaseSeparationProofPath []ProofStep\n\tCaptureDecision string\n")
	out.WriteString("}\n\n")
	out.WriteString("var Expanded = []ASTNode{\n")
	for _, node := range ir.AST {
		emitNode(&out, node, 1)
	}
	out.WriteString("}\n\n")
	out.WriteString("var Terminal = TerminalRecord{\n")
	out.WriteString("\tSchema: ")
	out.WriteString(strconv.Quote(ir.Terminal.Schema))
	out.WriteString(",\n\tDecision: ")
	out.WriteString(strconv.Quote(string(ir.Terminal.Decision)))
	out.WriteString(",\n\tStage: ")
	out.WriteString(strconv.Quote(ir.Terminal.Stage))
	out.WriteString(",\n\tStep: ")
	out.WriteString(strconv.Quote(ir.Terminal.Step))
	out.WriteString(",\n\tReason: ")
	out.WriteString(strconv.Quote(ir.Terminal.Reason))
	out.WriteString(",\n\tUnknownClass: ")
	out.WriteString(strconv.Quote(ir.Terminal.UnknownClass))
	out.WriteString(",\n\tNextOperation: ")
	out.WriteString(strconv.Quote(ir.Terminal.NextOperation))
	out.WriteString(",\n\tBlockedBy: ")
	out.WriteString(quoteStrings(ir.Terminal.BlockedBy))
	out.WriteString(",\n\tCounterexample: ")
	out.WriteString(strconv.Quote(ir.Terminal.Counterexample))
	out.WriteString(",\n\tCounterexampleDigest: ")
	out.WriteString(strconv.Quote(ir.Terminal.CounterexampleDigest))
	out.WriteString(",\n\tPhaseSeparationProofPath: []ProofStep{\n")
	for _, proof := range ir.Terminal.PhaseSeparationProofPath {
		out.WriteString("\t\t{Step: ")
		out.WriteString(strconv.Quote(proof.Step))
		out.WriteString(", From: ")
		out.WriteString(strconv.Quote(proof.From))
		out.WriteString(", To: ")
		out.WriteString(strconv.Quote(proof.To))
		out.WriteString(", Rule: ")
		out.WriteString(strconv.Quote(proof.Rule))
		out.WriteString(", NodeID: ")
		out.WriteString(strconv.Quote(proof.NodeID))
		out.WriteString(", FromStage: ")
		out.WriteString(strconv.Itoa(proof.FromStage))
		out.WriteString(", ToStage: ")
		out.WriteString(strconv.Itoa(proof.ToStage))
		out.WriteString("},\n")
	}
	out.WriteString("\t},\n\tCaptureDecision: ")
	out.WriteString(strconv.Quote(ir.Terminal.CaptureDecision))
	out.WriteString(",\n}\n\n")
	out.WriteString("func main() {\n\tfmt.Println(Terminal.Decision)\n}\n")
	return []byte(out.String())
}

func emitNode(out *strings.Builder, node ASTNode, depth int) {
	indent := strings.Repeat("\t", depth)
	out.WriteString(indent)
	out.WriteString("{Kind: ")
	out.WriteString(strconv.Quote(node.Kind))
	out.WriteString(", ID: ")
	out.WriteString(strconv.Quote(node.ID))
	out.WriteString(", OriginalName: ")
	out.WriteString(strconv.Quote(node.OriginalName))
	out.WriteString(", EffectiveName: ")
	out.WriteString(strconv.Quote(node.EffectiveName))
	out.WriteString(", Value: ")
	out.WriteString(strconv.Quote(node.Value))
	out.WriteString(", Stage: ")
	out.WriteString(strconv.Itoa(node.Stage))
	out.WriteString(", OriginIdentity: ")
	out.WriteString(strconv.Quote(node.OriginIdentity))
	out.WriteString(", StableIdentity: ")
	out.WriteString(strconv.Quote(node.StableIdentity))
	out.WriteString(", CaptureDecision: ")
	out.WriteString(strconv.Quote(node.CaptureDecision))
	if len(node.Children) > 0 {
		out.WriteString(", Children: []ASTNode{\n")
		for _, child := range node.Children {
			emitNode(out, child, depth+1)
		}
		out.WriteString(indent)
		out.WriteString("}")
	}
	out.WriteString("},\n")
}

func quoteStrings(values []string) string {
	var out strings.Builder
	out.WriteString("[]string{")
	for index, value := range values {
		if index > 0 {
			out.WriteString(", ")
		}
		out.WriteString(strconv.Quote(value))
	}
	out.WriteString("}")
	return out.String()
}
